// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseSidebar: typeof import('./components/ui/base-sidebar/base-sidebar.vue')['default']
    BaseTopbar: typeof import('./components/ui/base-topbar/base-topbar.vue')['default']
    BaseTopbarNavMenu: typeof import('./components/ui/base-topbar-nav-menu/base-topbar-nav-menu.vue')['default']
    BaseTopbarNavMenuItem: typeof import('./components/ui/base-topbar-nav-menu/base-topbar-nav-menu-item.vue')['default']
    BrandLogo1: typeof import('./components/app/brand-logo/brand-logo-1.vue')['default']
    LayoutDefault: typeof import('./components/layouts/layout-default.vue')['default']
    LayoutTopHeader: typeof import('./components/layouts/layout-top-header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
