// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseSidebar: typeof import('./components/ui/base-sidebar/base-sidebar.vue')['default']
    BaseTopbar: typeof import('./components/ui/base-topbar/base-topbar.vue')['default']
    NavSidebar: typeof import('./components/app/nav-sidebar/nav-sidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
