// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppLayout: typeof import('./components/layouts/app-layout.vue')['default']
    BaseButton: typeof import('./components/ui/base-button/base-button.vue')['default']
    BaseCard: typeof import('./components/ui/base-card/base-card.vue')['default']
    BaseCardBody: typeof import('./components/ui/base-card/base-card-body.vue')['default']
    BaseCardTitle: typeof import('./components/ui/base-card/base-card-title.vue')['default']
    BaseDatatable: typeof import('./components/ui/base-datatable/base-datatable.vue')['default']
    BaseDatatableTableBody: typeof import('./components/ui/base-datatable/base-datatable-table-body.vue')['default']
    BaseDatatableTableFoot: typeof import('./components/ui/base-datatable/base-datatable-table-foot.vue')['default']
    BaseDatatableTableHead: typeof import('./components/ui/base-datatable/base-datatable-table-head.vue')['default']
    BaseInputField: typeof import('./components/ui/base-input-field/base-input-field.vue')['default']
    BaseLink: typeof import('./components/ui/base-link/base-link.vue')['default']
    BaseModal: typeof import('./components/ui/base-modal/base-modal.vue')['default']
    BaseModalBody: typeof import('./components/ui/base-modal/base-modal-body.vue')['default']
    BaseModalFooter: typeof import('./components/ui/base-modal/base-modal-footer.vue')['default']
    BaseModalHeader: typeof import('./components/ui/base-modal/base-modal-header.vue')['default']
    BasePagination: typeof import('./components/ui/base-pagination/base-pagination.vue')['default']
    BaseSidebar: typeof import('./components/ui/base-sidebar/base-sidebar.vue')['default']
    BaseSidebarMenuItem: typeof import('./components/ui/base-sidebar/base-sidebar-menu-item.vue')['default']
    BaseTopbar: typeof import('./components/ui/base-topbar/base-topbar.vue')['default']
    BaseTopbarNavMenu: typeof import('./components/ui/base-topbar-nav-menu/base-topbar-nav-menu.vue')['default']
    BrandLogo1: typeof import('./components/app/brand-logo/brand-logo-1.vue')['default']
    CardContainer: typeof import('./components/ui/card-container/card-container.vue')['default']
    DashboardView: typeof import('./modules/dashboard/views/DashboardView.vue')['default']
    LayoutDefault: typeof import('./components/layouts/layout-default.vue')['default']
    LayoutTopHeaderContentOnly: typeof import('./components/layouts/layout-top-header-content-only.vue')['default']
    LayoutTopHeaderWithSidebar: typeof import('./components/layouts/layout-top-header-with-sidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarHeaderVehicleInfo: typeof import('./modules/vehicles/components/sidebar-header-vehicle-info.vue')['default']
    SidebarNavMenu: typeof import('./components/app/sidebar-nav-menu/sidebar-nav-menu.vue')['default']
    TestLoading: typeof import('./components/app/test-loading.vue')['default']
    TopbarNavMenu: typeof import('./components/app/topbar-nav-menu/topbar-nav-menu.vue')['default']
    VehicleCreateView: typeof import('./modules/vehicles/views/VehicleCreateView.vue')['default']
    VehicleGasLogView: typeof import('./modules/vehicles/views/VehicleGasLogView.vue')['default']
    VehicleMainView: typeof import('./modules/vehicles/views/VehicleMainView.vue')['default']
    VehicleProfileView: typeof import('./modules/vehicles/views/VehicleProfileView.vue')['default']
    VehiclesListView: typeof import('./modules/vehicles/views/VehiclesListView.vue')['default']
  }
}

export {}
